services:
  web:
    image: rhub/rhub2-web:0.0.1
    build:
      context: app
    ports:
      - "3000:3000"
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
