volumes:
  dbdata:
  uploads:

services:
  web:
    image: rhub/rhub2-web:0.99.0
    build:
      context: app
    command: nodemon bin/www.js
    volumes:
      - ./app:/src
      - uploads:/uploads
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - MAILGUN_KEY=${MAILGUN_KEY}
      - DATABASE_URL=postgres://postgres:secret@db:5432/postgres
      - NODE_ENV=development
    ports:
      - "3000:80"

  # For debugging, to connect to the web app or the DB
  shell:
    image: rhub/rhub2-shell:0.99.0
    build:
      context: shell
    volumes:
      - ./shell/DESCRIPTION:/DESCRIPTION
      - ./shell/R:/R
    environment:
      - DATABASE_URL=postgres://postgres:secret@db:5432/postgres
      - RHUB2_TOKEN=2f646deb-cbe1-443e-8d4a-890534c96633

  db:
    image: "postgres:16.2-bookworm"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql
      - ./db/create.sql:/docker-entrypoint-initdb.d/1-create.sql
