services:
  web:
    command: nodemon bin/www.js
    volumes:
      - ./app:/src
    environment:
      - PRIVATE_KEY_PATH=/run/secrets/ghappkey
      - MAILGUN_KEY_PATH=/run/secrets/mailguntoken

  shell:
    volumes:
      - ./shell/DESCRIPTION:/DESCRIPTION
      - ./shell/R:/R
    environment:
      - RHUB2_TOKEN=2f646deb-cbe1-443e-8d4a-890534c96633
