kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: db-sc
provisioner: file.csi.azure.com
allowVolumeExpansion: true
mountOptions:
  - nconnect=4
  - noresvport
  - actimeo=30
parameters:
  protocol: nfs
  skuName: Premium_LRS
reclaimPolicy: Retain
