apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dbdata
  name: dbdata
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: db-sc
  resources:
    requests:
      storage: 5Gi
status: {}
