apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s
    kompose.service.group: rhub2
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: shell
  name: shell
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shell
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s
        kompose.service.group: rhub2
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/rhub-app-default: "true"
        io.kompose.service: shell
    spec:
      containers:
        - env:
            - name: PG_HOST
              value: db
            - name: PG_PASS_FILE
              value: /db-password
            - name: PG_USER
              value: postgres
          image: rhub/rhub2-shell:0.0.6
          name: shell
          resources: {}
      restartPolicy: Always
status: {}
